#!/usr/bin/env python3
"""Generate a machine-readable snapshot of the orchestrator's configured surface.

The snapshot captures CLI subcommands, scheduled jobs (from the repo-owned
``scheduled_jobs`` registry, not machine-local launchd state), pyproject
entrypoints, design doc inventory, and source modules. All five fields are
compared against a committed baseline in CI via ``tests/test_doc_alignment.py``
(``test_snapshot_not_stale``) — if any change without updating the baseline,
the test fails with a clear diff.

Usage::

    python scripts/generate_strategy_snapshot.py            # print JSON to stdout
    python scripts/generate_strategy_snapshot.py --update   # overwrite the baseline
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BASELINE = REPO / "data" / "strategy_snapshot.json"


def _cli_subcommands() -> list[str]:
    """Extract CLI subcommand names from cli.py source."""
    cli_src = (REPO / "src" / "renquant_orchestrator" / "cli.py").read_text()
    return sorted(re.findall(r'add_parser\(\s*\n?\s*"([^"]+)"', cli_src))


def _pyproject_entrypoints() -> dict[str, str]:
    """Read [project.scripts] from pyproject.toml."""
    toml_path = REPO / "pyproject.toml"
    text = toml_path.read_text()
    in_scripts = False
    entries: dict[str, str] = {}
    for line in text.splitlines():
        if line.strip() == "[project.scripts]":
            in_scripts = True
            continue
        if in_scripts:
            if line.startswith("["):
                break
            m = re.match(r'(\S+)\s*=\s*"([^"]+)"', line.strip())
            if m:
                entries[m.group(1)] = m.group(2)
    return entries


def _scheduled_jobs() -> list[str]:
    """List job_ids from the repo-owned scheduled-job registry.

    Sourced from ``renquant_orchestrator.scheduled_jobs`` (not local
    ``~/Library/LaunchAgents`` state, which is machine-local and would make
    this comparison meaningless in CI / on a different developer's laptop).
    """
    sys.path.insert(0, str(REPO / "src"))
    from renquant_orchestrator.scheduled_jobs import scheduled_jobs as _registry

    return sorted(job.job_id for job in _registry())


def _design_docs() -> list[str]:
    """List design doc filenames on disk."""
    design_dir = REPO / "doc" / "design"
    if not design_dir.exists():
        return []
    return sorted(p.name for p in design_dir.iterdir() if p.suffix == ".md")


def _source_modules() -> list[str]:
    """List Python modules under src/renquant_orchestrator/."""
    pkg = REPO / "src" / "renquant_orchestrator"
    modules: list[str] = []
    for p in sorted(pkg.rglob("*.py")):
        rel = p.relative_to(pkg)
        mod = str(rel).replace("/", ".").removesuffix(".py")
        if mod == "__init__":
            continue
        if mod.startswith("__pycache__"):
            continue
        modules.append(mod)
    return modules


def generate() -> dict:
    return {
        "_comment": "Auto-generated by scripts/generate_strategy_snapshot.py. Do not edit.",
        "cli_subcommands": _cli_subcommands(),
        "pyproject_entrypoints": _pyproject_entrypoints(),
        "scheduled_jobs": _scheduled_jobs(),
        "design_docs": _design_docs(),
        "source_modules": _source_modules(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update", action="store_true",
        help=f"Overwrite {BASELINE.relative_to(REPO)}",
    )
    args = parser.parse_args()

    snapshot = generate()

    if args.update:
        BASELINE.parent.mkdir(parents=True, exist_ok=True)
        BASELINE.write_text(json.dumps(snapshot, indent=2) + "\n")
        print(f"Updated {BASELINE.relative_to(REPO)}", file=sys.stderr)
        return 0

    print(json.dumps(snapshot, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
