#!/usr/bin/env python3
"""Generate a machine-readable snapshot of the orchestrator's configured surface.

The snapshot captures CLI subcommands, scheduled jobs, pyproject entrypoints,
and design doc inventory. A committed baseline is compared in CI via
``tests/test_doc_alignment.py`` — if any of these change without updating the
baseline, the test fails with a clear diff.

Usage::

    python scripts/generate_strategy_snapshot.py            # print JSON to stdout
    python scripts/generate_strategy_snapshot.py --update   # overwrite the baseline
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BASELINE = REPO / "data" / "strategy_snapshot.json"


def _cli_subcommands() -> list[str]:
    """Extract CLI subcommand names from cli.py source."""
    cli_src = (REPO / "src" / "renquant_orchestrator" / "cli.py").read_text()
    return sorted(re.findall(r'add_parser\(\s*\n?\s*"([^"]+)"', cli_src))


def _pyproject_entrypoints() -> dict[str, str]:
    """Read [project.scripts] from pyproject.toml."""
    toml_path = REPO / "pyproject.toml"
    text = toml_path.read_text()
    in_scripts = False
    entries: dict[str, str] = {}
    for line in text.splitlines():
        if line.strip() == "[project.scripts]":
            in_scripts = True
            continue
        if in_scripts:
            if line.startswith("["):
                break
            m = re.match(r'(\S+)\s*=\s*"([^"]+)"', line.strip())
            if m:
                entries[m.group(1)] = m.group(2)
    return entries


def _scheduled_jobs() -> list[str]:
    """List installed com.renquant.* launchd plists."""
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    if not agents_dir.exists():
        return []
    names: list[str] = []
    for p in sorted(agents_dir.glob("com.renquant.*.plist")):
        stem = p.stem
        if stem.endswith(".disabled") or ".bak" in stem:
            continue
        name = stem.removeprefix("com.renquant.")
        names.append(name)
    return sorted(set(names))


def _design_docs() -> list[str]:
    """List design doc filenames on disk."""
    design_dir = REPO / "doc" / "design"
    if not design_dir.exists():
        return []
    return sorted(p.name for p in design_dir.iterdir() if p.suffix == ".md")


def _source_modules() -> list[str]:
    """List Python modules under src/renquant_orchestrator/."""
    pkg = REPO / "src" / "renquant_orchestrator"
    modules: list[str] = []
    for p in sorted(pkg.rglob("*.py")):
        rel = p.relative_to(pkg)
        mod = str(rel).replace("/", ".").removesuffix(".py")
        if mod == "__init__":
            continue
        if mod.startswith("__pycache__"):
            continue
        modules.append(mod)
    return modules


def generate() -> dict:
    return {
        "_comment": "Auto-generated by scripts/generate_strategy_snapshot.py. Do not edit.",
        "cli_subcommands": _cli_subcommands(),
        "pyproject_entrypoints": _pyproject_entrypoints(),
        "scheduled_jobs": _scheduled_jobs(),
        "design_docs": _design_docs(),
        "source_modules": _source_modules(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update", action="store_true",
        help=f"Overwrite {BASELINE.relative_to(REPO)}",
    )
    args = parser.parse_args()

    snapshot = generate()

    if args.update:
        BASELINE.parent.mkdir(parents=True, exist_ok=True)
        BASELINE.write_text(json.dumps(snapshot, indent=2) + "\n")
        print(f"Updated {BASELINE.relative_to(REPO)}", file=sys.stderr)
        return 0

    print(json.dumps(snapshot, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
